const KeyData = [
  { key: "A", letter: "Z" },
  { key: "B", letter: "" },
  { key: "C", letter: "" },
  { key: "D", letter: "" },
  { key: "E", letter: "" },
  { key: "F", letter: "" },
  { key: "G", letter: "" },
  { key: "H", letter: "" },
  { key: "I", letter: "" },
  { key: "J", letter: "" },
  { key: "K", letter: "" },
  { key: "L", letter: "" },
  { key: "M", letter: "" },
  { key: "N", letter: "" },
  { key: "O", letter: "" },
  { key: "P", letter: "" },
  { key: "Q", letter: "" },
  { key: "R", letter: "" },
  { key: "S", letter: "" },
  { key: "T", letter: "" },
  { key: "U", letter: "" },
  { key: "V", letter: "" },
  { key: "W", letter: "" },
  { key: "X", letter: "" },
  { key: "Y", letter: "" },
  { key: "Z", letter: "" }
];
export default KeyData;
